### PR TITLE
Dev 

### PR DESCRIPTION
**Pull request by yokozuna753**
created missing models, migrations, and added necessary validators to dev.

### CODE REVIEW

**Comment by yokozuna753** [comment]
Good to go

**Comment by gabrielsalfaro** [comment]
my comment

**Review by gabrielsalfaro — APPROVED** [review]
looks good

**Comment by Crios223** [comment]
Purrrrfect 🐈

**Review by Crios223 — COMMENTED** [review]
A Okay!

**Review by Crios223 — COMMENTED** [review]
Perfecto!

**Pull request merged**
